version: "3.8"
services:
  mysql:
    image: uchechi/lotto-db:latest
    build: ./db
    volumes:
      - type: volume
        source: lotto-vol
        target: /var/lib/mysql
    networks:
      - "lotto-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: lotto_db
  front-end:
    image: uchechi/lotto-front:latest
    build: ./front-end
    networks:
      - "lotto-net"
    depends_on:
      - "mysql"
      - "lotto-api"
      - "prize-api"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  lotto-api:
    image: uchechi/lotto-lotto:latest
    build: ./lotto-api
    networks:
      - "lotto-net"
      lottodraw-api:
    image: uchechi/lotto-lottodraw:latest
    build: ./lottodraw-api
    networks:
      - "lotto-net"
  prize-api:
    image: uchechi/lotto-prize:latest
    build: ./prize-api
    networks:
      - "lotto-net"
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - "lotto-net"
    depends_on:
      - "front-end"
volumes:
  lotto-vol:
networks:
  lotto-net: