- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/travz/lotto
  - name: clone repo
    git:
      repo: https://github.com/0xUO/lotto
      dest: /home/travz/lotto
      clone: yes
  vars:
    docker_user: uche

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: uche
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: uche